// Códigos de error estables para el cliente. El mensaje puede cambiar; el código no.
export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL: "INTERNAL",

  // --- Dominio catálogo / inventario (Prompt 2) ---
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  VARIANT_NOT_FOUND: "VARIANT_NOT_FOUND",
  SKU_ALREADY_EXISTS: "SKU_ALREADY_EXISTS",
  BARCODE_ALREADY_EXISTS: "BARCODE_ALREADY_EXISTS",
  PRICE_INVALID: "PRICE_INVALID",
  COST_INVALID: "COST_INVALID",
  INVENTORY_INSUFFICIENT: "INVENTORY_INSUFFICIENT",
  INVENTORY_ADJUSTMENT_INVALID: "INVENTORY_ADJUSTMENT_INVALID",
  INVENTORY_RESERVATION_NOT_FOUND: "INVENTORY_RESERVATION_NOT_FOUND",
  INVENTORY_RESERVATION_ALREADY_RELEASED: "INVENTORY_RESERVATION_ALREADY_RELEASED",
  TRANSFER_INVALID_STATE: "TRANSFER_INVALID_STATE",
  TRANSFER_SAME_WAREHOUSE: "TRANSFER_SAME_WAREHOUSE",
  STOCK_COUNT_INVALID_STATE: "STOCK_COUNT_INVALID_STATE",
  STOCK_COUNT_ALREADY_APPLIED: "STOCK_COUNT_ALREADY_APPLIED",

  // --- Compras (Prompt 3) ---
  SUPPLIER_NOT_FOUND: "SUPPLIER_NOT_FOUND",
  PURCHASE_ORDER_NOT_FOUND: "PURCHASE_ORDER_NOT_FOUND",
  PURCHASE_INVALID_STATE: "PURCHASE_INVALID_STATE",
  PURCHASE_ALREADY_POSTED: "PURCHASE_ALREADY_POSTED",

  // --- Ventas / pedidos (Prompt 4) ---
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_INVALID_STATE: "ORDER_INVALID_STATE",
  ORDER_EMPTY: "ORDER_EMPTY",
  PRICE_NOT_FOUND: "PRICE_NOT_FOUND",
  CREDIT_LIMIT_EXCEEDED: "CREDIT_LIMIT_EXCEEDED",

  // --- Pagos / caja (Prompt 5) ---
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_EXCEEDS_TOTAL: "PAYMENT_EXCEEDS_TOTAL",
  PAYMENT_INVALID_STATE: "PAYMENT_INVALID_STATE",
  CASH_REGISTER_NOT_FOUND: "CASH_REGISTER_NOT_FOUND",
  CASH_SESSION_NOT_FOUND: "CASH_SESSION_NOT_FOUND",
  CASH_SESSION_NOT_OPEN: "CASH_SESSION_NOT_OPEN",
  CASH_SESSION_ALREADY_OPEN: "CASH_SESSION_ALREADY_OPEN",
  CASH_SESSION_REQUIRED: "CASH_SESSION_REQUIRED",

  // --- Notas de venta (Prompt 7) ---
  SALE_NOTE_NOT_FOUND: "SALE_NOTE_NOT_FOUND",
  SALE_NOTE_INVALID_STATE: "SALE_NOTE_INVALID_STATE",
  SALE_NOTE_ALREADY_ISSUED: "SALE_NOTE_ALREADY_ISSUED",

  // --- Devoluciones / notas de crédito (Prompt 8) ---
  CREDIT_NOTE_NOT_FOUND: "CREDIT_NOTE_NOT_FOUND",
  CREDIT_NOTE_EMPTY: "CREDIT_NOTE_EMPTY",
  RETURN_EXCEEDS_SOLD: "RETURN_EXCEEDS_SOLD",
  SALE_NOTE_ITEM_NOT_FOUND: "SALE_NOTE_ITEM_NOT_FOUND",

  // --- Notificaciones (Prompt 9) ---
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
